project_id = "jstsrgyxrrlklnzgsihd"

[functions.diagnose-gestao-rls]
verify_jwt = false

[functions.health-check-sync]
verify_jwt = false

[functions.receive-schema-from-tabulador]
verify_jwt = false

[functions.sync-bitrix-spas]
verify_jwt = false

[functions.enrich-leads-from-bitrix]
verify_jwt = false