project_id = "jstsrgyxrrlklnzgsihd"

[functions.diagnose-gestao-rls]
verify_jwt = false

[functions.health-check-sync]
verify_jwt = false

[functions.receive-schema-from-tabulador]
verify_jwt = false

[functions.sync-bitrix-spas]
verify_jwt = false

[functions.enrich-leads-from-bitrix]
verify_jwt = false

[functions.enrich-pending-leads]
verify_jwt = false

[functions.ai-database-inspector]
verify_jwt = false

[functions.ai-log-aggregator]
verify_jwt = false

[functions.ai-source-analyzer]
verify_jwt = false

[functions.ai-analyze-error]
verify_jwt = false

[functions.apply-fix]
verify_jwt = false

[functions.rollback-fix]
verify_jwt = false