project_id = "ngestyxtopvfeyenyvgt"

# Edge Functions configuration
# Disable JWT verification for webhook receivers and sync functions

[functions.sync-tabulador]
verify_jwt = false

[functions.webhook-receiver]
verify_jwt = false

[functions.tabulador-webhook]
verify_jwt = false

[functions.process-sync-queue]
verify_jwt = false

[functions.tabulador-export]
verify_jwt = false